# 0 Sample Data Generation

In this notebook we generate sample data for each state of both the trip and weather (and merged) datasets for an easier and faster exemplary compliation of our notebooks. Please keep in mind that we sample the data randomly, therefore the sampled data is solely an exemplary (not perfect) representation of our datasets and some patterns etc. are not represented in the sampled datasets.

For the sampling we decided to sample the datasets down to a total of approx. 10.000 - 15.000 rows, keeping all columns.

All of our data can be found in the following sciebo folder: https://uni-koeln.sciebo.de/s/z5xgdGosd9y9c4e (Password: AAA2026)

In [1]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Import packages                         #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

import pandas as pd

# reset working dir
import os
from pathlib import Path

In [2]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Reset working directory                 #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

import __main__
_nb = getattr(__main__, "__vsc_ipynb_file__", None) or os.environ.get("JPY_SESSION_NAME")
_start = Path(_nb).resolve().parent if _nb else Path.cwd()
os.chdir(next(p for p in [_start, *_start.parents] if (p / "pyproject.toml").exists()))
print(f"Working directory: {os.getcwd()}")

Working directory: C:\Users\Yannick Herrmann\Documents\Uni\AAA\AAA_Project\AAA_TA_2026

In [3]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Configs                                 #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

SAMPLE_FRAC = 0.002
random_seed = 42
OUTPUT_DIR = "data/samples"

In [4]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Sampling function                       #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

def sample_merged_data(df, frac, random_state, output_file_name):
    output_path = f"{OUTPUT_DIR}/{output_file_name}"
    sample = df.sample(frac=frac, random_state=random_state)
    sample.to_parquet(output_path, index=False)
    print(f"Sampled {len(sample):,} rows ({frac:.2%} of total)")
    print(f"Saved to {output_path}")
    return sample

## 0.1 Raw Chicago Trip Data

First we sample the **raw** trip data downloaded from the webportal of the city of chicago: https://data.cityofchicago.org/Transportation/Taxi-Trips-2024-/ajtu-isnz/about_data (downloaded on 05.05.2026).

The trip data fetching can be found here: [Raw Chicago Trip Data](01_Preprocessing/01_01_Fetch_Trip_Data.ipynb)

In [5]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Load raw trip data                      #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

raw_trip_data = pd.read_parquet("data/trips/01_01_fetch_trip_data.parquet")
raw_trip_data.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,...,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location
0,0275e2d8147a31e1ce320c5fb15f9910563cafe1,84957c8960b674346784746bbc1d48cafff4976b162323...,2025-01-01,2025-01-01 00:15:00,758.0,2.93,NaN,NaN,8.0,8.0,...,0.0,9.75,Prcard,Flash Cab,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.899602,-87.633308,POINT (-87.6333080367 41.899602111)
1,05aa05bf6f3ec476715fad9f706bd137e08e00b7,0cbf5c0f6aca3628d77c7b6fe89715757ed402a70b0f8b...,2025-01-01,2025-01-01 00:15:00,1233.0,13.66,NaN,NaN,76.0,6.0,...,5.0,48.60,Credit Card,Globe Taxi,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),41.944227,-87.655998,POINT (-87.6559981815 41.9442266014)
2,060f692c4ca69e552c07a97c99715ad51112470e,e533bfdc483206f9c02c1c879a118d88f0a3ca1cd2703f...,2025-01-01,2025-01-01 00:00:00,6.0,0.00,NaN,NaN,6.0,6.0,...,0.0,30.50,Credit Card,Flash Cab,41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),41.944227,-87.655998,POINT (-87.6559981815 41.9442266014)
3,0b2d1368456148b049af41dc8aa565d688081756,2d5029b701200a2ab66bd5071f743efe20a3036597d2b3...,2025-01-01,2025-01-01 00:00:00,11.0,0.00,NaN,NaN,77.0,77.0,...,0.0,25.62,Credit Card,Sun Taxi,41.986712,-87.663416,POINT (-87.6634164054 41.9867117999),41.986712,-87.663416,POINT (-87.6634164054 41.9867117999)
4,17365c83264f028a307ac70308d770fe03bcbcae,c3f8e0b6712bf3ea80e75ddde065b0ed42aa530e8c40cb...,2025-01-01,2025-01-01 00:15:00,985.0,3.22,NaN,NaN,8.0,7.0,...,0.0,55.00,Cash,City Service,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.922686,-87.649489,POINT (-87.6494887289 41.9226862843)

In [6]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Sample raw trip data                    #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

trip_sample = raw_trip_data.sample(frac=SAMPLE_FRAC, random_state=random_seed)

trip_sample.to_parquet("data/samples/SAMPLE_01_01_fetch_trip_data.parquet", index=False)

print(f"Sampled {len(trip_sample):,} rows ({SAMPLE_FRAC:.2%} of total)")
print(f"Saved to data/samples/SAMPLE_01_01_fetch_trip_data.parquet")

Sampled 13,652 rows (0.20% of total)
Saved to data/samples/SAMPLE_01_01_fetch_trip_data.parquet

## 0.2 Raw Chicago Weather Data

For the weather data, we decided to not sample both `data/weather/weather_daily.parquet`and `data/weather/weather_hourly.parquet` since these two datasets have sizes of 69KB and 1.9MB. Therefore the full datasets are no problem for exemplary compilation of code.

# 0.3 Cleaned Trip Data

Now we sample the **cleaned** taxi trip data.

The trip data cleaning can be found here: [Trip Data Cleaning](01_Preprocessing/01_03_Trip_Data_Cleanup.ipynb)

In [8]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Load cleaned trip data                  #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

cleaned_trip_data = pd.read_parquet("data/trips/01_04_trips_clean.parquet")

cleaned_trip_data.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_community_area,dropoff_community_area,fare,tips,...,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,pickup_h3_res6,dropoff_h3_res6,pickup_h3_res7,dropoff_h3_res7
0,8150f6109ac87bd76dc8d7bea6211b650d94fce7,6213661be7873fbf6ccb2cdbf51f6d4882bac07a52b602...,2025-08-16 08:45:00,2025-08-16 09:15:00,1798.0,17.40,76,8,42.25,9.55,...,Credit Card,Taxicab Insurance Agency Llc,41.979071,-87.903040,41.893216,-87.637844,86275935fffffff,862664c1fffffff,87275936bffffff,872664c1effffff
1,64a7e947c344f5e1790e977fc2532d332f527e80,6cf97b9e8e3e1c183c090cdd868df381de772a52987239...,2025-02-14 08:00:00,2025-02-14 08:15:00,1263.0,9.78,32,6,26.50,0.00,...,Prcard,Flash Cab,41.878866,-87.625192,41.944227,-87.655998,862664c1fffffff,862664c17ffffff,872664c18ffffff,872664c14ffffff
2,e1ef4ba4c5065c284c3922e5889287aee0786989,a62df4e9bfec5f3babb7922b1346263cce5c3116fa5fa3...,2025-05-16 20:30:00,2025-05-16 21:00:00,2135.0,16.07,76,8,41.25,9.15,...,Credit Card,Medallion Leasin,41.979071,-87.903040,41.899156,-87.626211,86275936fffffff,862664c17ffffff,87275936bffffff,872664c1effffff
3,2bcc7be5ca4bbbf67abdfe8848d8926eba35252b,4ecfd5dfe736c290319189484af9fa4ca06dbbadf5585b...,2025-07-07 10:00:00,2025-07-07 10:15:00,525.0,1.12,28,8,7.00,3.00,...,Credit Card,Flash Cab,41.885300,-87.642808,41.892508,-87.626215,862664cafffffff,862664c1fffffff,872664cabffffff,872664c1effffff
4,bff26362297fcfc5f3043d7c452e8a7f9080392d,9757aea9fe516d22d0ddd0e77f1cb8a54a3e5f2b91e097...,2025-10-08 15:00:00,2025-10-08 15:45:00,2925.0,12.30,76,5,34.00,5.92,...,Credit Card,Flash Cab,41.980264,-87.913625,41.947792,-87.683835,862759347ffffff,862664ca7ffffff,87275936bffffff,872664ca5ffffff

In [9]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Sample cleaned trip data                #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

trip_sample = cleaned_trip_data.sample(frac=SAMPLE_FRAC, random_state=random_seed)

trip_sample.to_parquet("data/samples/SAMPLE_01_04_trips_clean.parquet", index=False)

print(f"Sampled {len(trip_sample):,} rows ({SAMPLE_FRAC:.2%} of total)")
print(f"Saved to data/samples/SAMPLE_01_04_trips_clean.parquet")

Sampled 22 rows (0.20% of total)
Saved to data/samples/SAMPLE_01_04_trips_clean.parquet

# 0.4 Merged Trip and Weather Data

After cleaning we merged the trip data with weather data.

The merging can be found in this notebook: [Trip Weather Data Merge](01_Preprocessing/01_05_Trips_Weather_Merge.ipynb)

In [11]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Load merged trip data                   #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

merged = pd.read_parquet("data/merged/01_05_trips_weather_merged.parquet")

In [12]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Sample merged data                      #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

trip_sample = merged.sample(frac=SAMPLE_FRAC, random_state=random_seed)

trip_sample.to_parquet("data/samples/SAMPLE_01_05_trips_weather_merged.parquet", index=False)

print(f"Sampled {len(trip_sample):,} rows ({SAMPLE_FRAC:.2%} of total)")
print(f"Saved to data/samples/SAMPLE_01_05_trips_weather_merged.parquet")

Sampled 22 rows (0.20% of total)
Saved to data/samples/SAMPLE_01_05_trips_weather_merged.parquet

# 0.4 Aggregated Data

Now we sample the aggregated trip and weather data.

The data aggregation can be found in this notebook: [Data Aggregation](01_Preprocessing/01_06_Data_Aggregation.ipynb)

In [13]:
#demand_hex_1h_h = pd.read_parquet("data/aggregated/hexagon/demand_hex_1h_high.parquet")
demand_hex_1h_m = pd.read_parquet("data/aggregated/hexagon/demand_hex_1h_medium.parquet")
demand_hex_1h_l = pd.read_parquet("data/aggregated/hexagon/demand_hex_1h_low.parquet")

In [14]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Sample aggregated data                  #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

# demand_sample_1h_h = sample_merged_data(
#     demand_hex_1h_h,
#     SAMPLE_FRAC,
#     random_seed,
#     "SAMPLE_demand_hex_1h_high.csv"
# )

demand_sample_1h_m = sample_merged_data(
    demand_hex_1h_m,
    SAMPLE_FRAC,
    random_seed,
    "SAMPLE_demand_hex_1h_medium.parquet"
)

demand_sample_1h_l = sample_merged_data(
    demand_hex_1h_l,
    SAMPLE_FRAC,
    random_seed,
    "SAMPLE_demand_hex_1h_low.parquet"
)

Sampled 4,889 rows (0.20% of total)
Saved to data/samples/SAMPLE_demand_hex_1h_medium.parquet
Sampled 718 rows (0.20% of total)
Saved to data/samples/SAMPLE_demand_hex_1h_low.parquet

In [15]:
#demand_hex_2h_h = pd.read_csv("data/aggregated/hexagon/demand_hex_2h_high.csv")
demand_hex_2h_m = pd.read_parquet("data/aggregated/hexagon/demand_hex_2h_medium.parquet")
demand_hex_2h_l = pd.read_parquet("data/aggregated/hexagon/demand_hex_2h_low.parquet")

In [16]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Sample aggregated data                  #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

# demand_sample_2h_h = sample_merged_data(
#     demand_hex_2h_h,
#     SAMPLE_FRAC,
#     random_seed,
#     "SAMPLE_demand_hex_2h_high.csv"
# )

demand_sample_2h_m = sample_merged_data(
    demand_hex_2h_m,
    SAMPLE_FRAC,
    random_seed,
    "SAMPLE_demand_hex_2h_medium.parquet"
)

demand_sample_2h_l = sample_merged_data(
    demand_hex_2h_l,
    SAMPLE_FRAC,
    random_seed,
    "SAMPLE_demand_hex_2h_low.parquet"
)

Sampled 4,889 rows (0.20% of total)
Saved to data/samples/SAMPLE_demand_hex_2h_medium.parquet
Sampled 718 rows (0.20% of total)
Saved to data/samples/SAMPLE_demand_hex_2h_low.parquet

In [17]:
#demand_hex_6h_h = pd.read_csv("data/aggregated/hexagon/demand_hex_6h_high.csv")
demand_hex_6h_m = pd.read_parquet("data/aggregated/hexagon/demand_hex_6h_medium.parquet")
demand_hex_6h_l = pd.read_parquet("data/aggregated/hexagon/demand_hex_6h_low.parquet")

In [18]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Sample aggregated data                  #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

# demand_sample_6h_h = sample_merged_data(
#     demand_hex_6h_h,
#     SAMPLE_FRAC,
#     random_seed,
#     "SAMPLE_demand_hex_6h_high.csv"
# )

demand_sample_6h_m = sample_merged_data(
    demand_hex_6h_m,
    SAMPLE_FRAC,
    random_seed,
    "SAMPLE_demand_hex_6h_medium.parquet"
)

demand_sample_6h_l = sample_merged_data(
    demand_hex_6h_l,
    SAMPLE_FRAC,
    random_seed,
    "SAMPLE_demand_hex_6h_low.parquet"
)

Sampled 4,889 rows (0.20% of total)
Saved to data/samples/SAMPLE_demand_hex_6h_medium.parquet
Sampled 718 rows (0.20% of total)
Saved to data/samples/SAMPLE_demand_hex_6h_low.parquet

In [19]:
#demand_hex_24h_h = pd.read_csv("data/aggregated/hexagon/demand_hex_24h_high.csv")
demand_hex_24h_m = pd.read_parquet("data/aggregated/hexagon/demand_hex_24h_medium.parquet")
demand_hex_24h_l = pd.read_parquet("data/aggregated/hexagon/demand_hex_24h_low.parquet")

In [20]:
# # # # # # # # # # # # # # # # # # # # # #
#                                         #
# Sample aggregated data                  #
#                                         #
# # # # # # # # # # # # # # # # # # # # # #

# demand_hex_24h_h = sample_merged_data(
#     demand_hex_24h_h,
#     SAMPLE_FRAC,
#     random_seed,
#     "SAMPLE_demand_hex_24h_high.csv"
# )

demand_hex_24h_m = sample_merged_data(
    demand_hex_24h_m,
    SAMPLE_FRAC,
    random_seed,
    "SAMPLE_demand_hex_24h_medium.parquet"
)

demand_hex_24h_l = sample_merged_data(
    demand_hex_24h_l,
    SAMPLE_FRAC,
    random_seed,
    "SAMPLE_demand_hex_24h_low.parquet"
)

Sampled 4,889 rows (0.20% of total)
Saved to data/samples/SAMPLE_demand_hex_24h_medium.parquet
Sampled 718 rows (0.20% of total)
Saved to data/samples/SAMPLE_demand_hex_24h_low.parquet